### ISSUE TITLE
Mazumder - Update QC slide deck + FDA Argos General Slides

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#169]
Add new content to the end of the slide deck: https://docs.google.com/presentation/d/1r-OzjynWBdg_FCCFP0PvEOuHGomPCPBm4nw-OWAQ63w/edit#slide=id.p

All slides need to be updated. But I can do this after you add your content. Once complete, please reassign to me. I will also add content, edit yours, and edit other existing content

**Comment by JingyueWu** [comment]
@steph-sing Could the new content be the genome assembly I performed? That said, I propose that I add:
1. Comparison between different platforms (i.e. Galaxy vs. HIVE vs. Pegasus) and assemblers (i.e. MEGAHIT, metaviralSPAdes, and SPAdes) 
2. _de novo_ and reference-guided genome assembly workflow 
3. Introduce Stanford QC platform for SARS-CoV-2

Please let me know what you think. If the above are approved, I can update by the end of 1/31, since I already have the content.

**Comment by steph-sing** [comment]
great start - please have a draft to me by this Friday Feb 3rd. I'll review and give feedback, and you can edit until Monday COB as needed.

**Comment by steph-sing** [comment]
Moving into Feb 2023 Task list
