### ISSUE TITLE
Mazumder - Select ngs data for Candida Auris, provide justification, and add data to ngsQC_HIVE

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#264]

**Comment by steph-sing** [comment]
@JingyueWu prioritize #3 in the list above

**Comment by steph-sing** [comment]
here is another reference genome cited by the group and under the same BioProject: https://www.ncbi.nlm.nih.gov/assembly/GCF_003013715.1/ @penningtonea can you please look into the this more?

**Comment by JingyueWu** [comment]
@steph-sing Status update (as of 5:30 pm April 11):

As instructed to prioritize 3), I have added the 117 SRAs into the [QC Organism Tracking](https://docs.google.com/spreadsheets/d/1Nf9Eey2ruwKRkoSMoNhGCAYmFAw2Wb73TzA3sYA3va0/edit#gid=1033412383). Since there are 117 total, which is a lot, I highlighted 10 SRAs in the same color for now. That way, it is easier for me to keep track of them as I run ngsQC on them. 

This afternoon, I finished running 20 SRAs (highlighted in green and pink on [QC Organism Tracking](https://docs.google.com/spreadsheets/d/1Nf9Eey2ruwKRkoSMoNhGCAYmFAw2Wb73TzA3sYA3va0/edit#gid=1033412383)). Their corresponding ngsQC metrics were entered on [ngsQC_HIVE](https://docs.google.com/spreadsheets/d/1DfwThciSxiQ2SZsTuuILuUh1iNGXTiJ5/edit?usp=sharing&ouid=112104108364280622172&rtpof=true&sd=true) (starting from row 2198) from V1.3 folder. 

I will continue this tomorrow. I foresee no blockers, but the part that took the longest time was to get those SRRs into HIVE.

**Comment by Jgergely11** [comment]
@JingyueWu Please resolve the issues outlined below
- [ ] Remove brackets in the organism name
- [ ] Fill out "lineage" column
- [ ] Fill out "taxid" column
- [ ] Fix formatting in "analysis_platform" column
- [ ] Fill out "analysis_platform_object_id"
- [ ] Fill out "strain" column
- [ ] Fix formatting in "bioproject" column 
- [ ] Fix formatting in "ngs_gc_content" column
- [ ] Fill out "instrument" column
- [ ] Fix formatting in all columns with pipes  (there needs to be a space after each | ). You can isolate your data and do a find and replace search. Replace "|" with "| "

**Comment by penningtonea** [comment]
> here is another reference genome cited by the group and under the same BioProject: https://www.ncbi.nlm.nih.gov/assembly/GCF_003013715.1/ @penningtonea can you please look into the this more?

Would you like me to QC this assembly and compare to GCA_002759435.2?

**Comment by JingyueWu** [comment]
@Jgergely11 Fixed. Please review.
