### ISSUE TITLE
Mazumder - Draft HIVE3 Constraints

### ISSUE THREAD

**Issue by penningtonea** [FDA-ARGOS/data.argosdb#278]
Draft constraints definitions for HIVE3 tools, specifically for the ARGOS one-click pipeline.

**Comment by penningtonea** [comment]
Move to July task list

**Comment by cwoodside1278** [comment]
@penningtonea update?

**Comment by penningtonea** [comment]
Not done, we can probably resume this after HIVE3 is revamped (estimated to be revamped by tomorrow, 2/9)

**Comment by penningtonea** [comment]
still waiting for hive 3 to be up and running. Will demonstrate how to get constraints for the data dictionary update through the type editor window.

**Comment by cwoodside1278** [comment]
is this done @penningtonea ?

**Comment by penningtonea** [comment]
@cwoodside1278 
data dictionary: We need assistance finishing the data dictionary column "pattern" for the variable datatypes from either Hadley or Jonathon.

HIVE3 platform instance: Constraints for individual fields in HIVE3 have not been drafted. Is this a major task at this point for the project?

**Comment by cwoodside1278** [comment]
That ticket was posted when Stephanie was here and hive3 had not yet crashed and has since taken 2 different meanings, one for the data dictionary patterns and one for the platform where you hover over a field and it gives you a brief description of what goes into the field.


Data dictionary - this part should be prioritized so that we can push the data dictionary to the server with all the required information. I believe that the "pattern" column for the data dictionary variables is required.
      - Christie has filled in the pattern column in the updated v1.6 Data Dictionary for the data push
      - Constraint column is not filled in. It says N/A.

Constraints field descriptions for the platform -  I'm not sure how urgent this is or if it's important to the paper. This task would be us coming up with definitions for the fields and inputting them into the type editor so that the next user can hover over the field and see what should go into it.

 We would need to confirm with Raja that we should prioritize this part. @rajamazumder can we discuss this in a future meeting?

**Comment by cwoodside1278** [comment]
We will not do the constraints fields descriptions for the platform. That is not a major priority right now @penningtonea So how do we go about updating the data dictionary with constraints?

**Comment by cwoodside1278** [comment]
I have updated the data dictionary with their constraints.
