### ISSUE TITLE
All teams - prepare slides for FDA monthly meeting in May

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#283]
Content/slides for each team member to create: 

- [x] QC protocol versions released to share point -  and highlight all of our protocols (please also upload on Sharepoint once finished) (@steph-sing)
- [x] v1.47 data release and data team updates (@steph-sing)
- [x] ~2 slides HIV EQAPOL data plan (@penningtonea) 
- [x] 1-2 CARD db slides and plan for siteQC (@penningtonea )
- [x] 1-2 slides describing HIVE frameshift and stop codon workflow (refer to the last section in the genome assembly protocol) (@JingyueWu)
- [x] 1-2 slide for status of pathogenic avian influenza (@JingyueWu, and meet with @steph-sing on the coming Monday 5/1 to discuss status) 
- [x] 1-2 slides of SNPEff workflow and results (ties into Frameshift and Stop Codon work (@stephenshank)
- [x] 1 slide introducing to FDA that the team is expanding by assembling bacteria genome assembly (@stephenshank, and please coordinate with @kacrandall team)
- [x] 6 month review (light overview)(@steph-sing)

All above slides (draft) need to be added to the deck (https://docs.google.com/presentation/d/1cvTGNieYeXhmsj3pc7XsZzujsaIT_lPVWu5Ud7sZFlo/edit?usp=sharing) by the end of 5/5.

**Comment by steph-sing** [comment]
Adding a note here: 
- [ ] potentially @penningtonea and I will prepare a slide re: poor quality of FASTA files for influenza in GISAID and how our protocols caught this.

**Comment by pmcneely** [comment]
When do you need these slides by? I'm confident we'll have material, but I'd like to know when we need to stop pushing the deployment and put the (hopefully best/completed) state into the deck.

**Comment by steph-sing** [comment]
Update for requested slide content based on the Bi-weekly PI meeting (5/3):

- All Draft slide content due to Steph by COB Friday 5/5. put all daft slides, here: [Monthly FDA Draft Meeting Slides](https://docs.google.com/presentation/d/1cvTGNieYeXhmsj3pc7XsZzujsaIT_lPVWu5Ud7sZFlo/edit?usp=sharing)

All Data Team Updates (@steph-sing):

- [ ] v1.48 data release + summary 
- [ ] Monthly tasks
- [ ] All protocol versions released to share point -  and highlight all of our protocols
- [ ] Plan for the next 6 months (end of slides)

All Other Slides and Content:
 
- [ ] 1-2 CARD db slides and plan for siteQC/assemblyQC - this in in context of expanding our current QC protocols, annotation, and gene specific information (@penningtonea)
- [ ] 1-2 slides describing HIVE frameshift and stop codon workflow (@JingyueWu @penningtonea)

- [ ] 1 slide for status of HPAI A(H5N1) summary (@JingyueWu review emails between Raja and Steph plus refer to decisions made during the PI meeting)

- [ ] 1-2 slides of SNPEff workflow and results (@stephenshank)

- [ ] 1-2 slides on BETSY Deployment + login and create user demo (@kee007ney @pmcneely)

- [ ] 1 slide on Galaxy installation status (@HadleyKing @stephenshank)


All above slides (draft) need to be added to the deck (https://docs.google.com/presentation/d/1cvTGNieYeXhmsj3pc7XsZzujsaIT_lPVWu5Ud7sZFlo/edit?usp=sharing) by the end of 5/5.
