### ISSUE TITLE
Christie - run all assemblies from argos in batch mode and collect data

### ISSUE THREAD

**Issue by cwoodside1278** [FDA-ARGOS/data.argosdb#418]
This is for HIVE 3 testing.

**Comment by penningtonea** [comment]
Initial pipeline runs were successful using one SRR file and one assembly file. Most organisms (if not all) will need to include multiple SRR files per assembly, depending on how many SRR files were used in generating the original assembly at UMD. Executing the pipeline using two SRR files introduced the following errors causing the pipeline to break: 

test 1 - entering SRR accessions directly into the pipeline failed.
error: ARGOS pipeline downloader engine experiencing issues indexing SRR files.

test 2 - downloading the SRR files via the external downloader for the purpose of using the HIVE IDs instead of directly entering the SRR accessions failed.
error: External downloader tool downloads SRR u-file but user cannot reprocess the u-file as an SRA file or convert to FASTQ file. The reprocessing and convert options are visible but the user cannot interact with those buttons.

**Comment by cwoodside1278** [comment]
Currently, the batch mode for the one-click pipeline is not working. The way that it is calling the information from the external downloader is incorrect. This issue has been brought to Vahan's attention so he is still working on it.

**Comment by penningtonea** [comment]
Batch mode protocol version 1 is live

**Comment by cwoodside1278** [comment]
batch mode protocol has been updated. A few successful batches, but there are still bugs. 
1) Error one: Comma error from genbank although all assemblies had been manually verified. A single computation was done with one of the error-assemblies, and it ran successfully. 
![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/144174658/da2df4b1-d22d-4246-bc5b-5d1c28c13bfc)

2) Updated batch mode protocol: [https://docs.google.com/document/d/1O-zW9tPRgiFbPpSwIlHPkJVCJ3DKTLSze3WMpBU00ow/edit#heading=h.gjdgxs](https://docs.google.com/document/d/1O-zW9tPRgiFbPpSwIlHPkJVCJ3DKTLSze3WMpBU00ow/edit#heading=h.gjdgxs)

**Comment by cwoodside1278** [comment]
We can run batches now
